# SITE CONFIGURATION
title: PHILIPPINE ISLAND LIVING # your site title
author: Kevin Olega # You :P
description: > # Meta description of Homepage
  Life In the Philippine Islands 
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://philippineislandliving.com" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Kevin Olega
  links:
    - http://kevinolega.com/now
    - https://twitter.com/kevinolega
    - https://www.facebook.com/ben.balter
    - https://www.instagram.com/kevinolega
    - http://minimalchanges.com
    - https://github.com/kevinolega
    - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Modern Jekyll theme focused on speed performance &amp; SEO best practices

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: philippineislandliving@gmail.com # email for form submission

twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
github_username:  janczizikow # replace with your_github_username or comment to remove link from footer
instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: philippineislandliving # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
